### ISSUE TITLE
TypeError: in method 'fvec_renorm_L2', argument 3 of type 'float *'

### ISSUE THREAD

**Issue by forrwill** [hannshu/stMSA#2]
Hi，I met a new error with "TypeError: in method 'fvec_renorm_L2', argument 3 of type 'float *'" . Is there any successtions for me?

The log is in
>>> INFO: Generate 963139 edges, 9.283 edges per spot.(1.565s)
>>> INFO: Generate 268777 edges, 9.188 edges per spot.(0.377s)
>>> INFO: Generate 359906 edges, 9.083 edges per spot.(0.650s)
>>> INFO: Generate 409368 edges, 8.771 edges per spot.(0.487s)
>>> INFO: Generate 185972 edges, 9.812 edges per spot.(0.309s)
>>> INFO: Generate 125326 edges, 9.677 edges per spot.(0.265s)
>>> INFO: Generate 257808 edges, 8.953 edges per spot.(0.560s)
>>> INFO: Generate 298623 edges, 9.887 edges per spot.(0.388s)
>>> INFO: Generate 117615 edges, 10.158 edges per spot.(0.072s)
>>> INFO: Generate 277573 edges, 9.459 edges per spot.(0.563s)
>>> INFO: Generate 437033 edges, 10.104 edges per spot.(0.678s)
>>> INFO: Generate 229297 edges, 9.524 edges per spot.(0.340s)
>>> INFO: Finish generate precluster embedding(129.432s)!
^M  0%|                                                                                                                 | 0/500 [00:00<?, ?it/s]^M  0%|                                                                                                                 | 0/500 [00:32<?, ?it/s]
Traceback (most recent call last):
  File "run_stMSA.py", line 41, in <module>
    adatas = train_integration(adatas, radius=30, device="cpu")
  File "~/soft/stMSA/train_integrate.py", line 77, in train_integration
    node_pairs = get_mnn_pairs(decomposed_x, node_id_map, k)
  File "~/soft/stMSA/stMSA/utils.py", line 78, in get_mnn_pairs
    distance_i2j, indices_i2j = find_similar_index(data_i, data_j, top_k)
  File "~/soft/stMSA/stMSA/utils.py", line 53, in find_similar_index
    faiss.normalize_L2(source)
  File "~/Miniconda3/envs/stMSA_env/lib/python3.10/site-packages/faiss/__init__.py", line 1304, in normalize_L2
    fvec_renorm_L2(x.shape[1], x.shape[0], swig_ptr(x))
  File "~/Miniconda3/envs/stMSA_env/lib/python3.10/site-packages/faiss/swigfaiss.py", line 1658, in fvec_renorm_L2
    return _swigfaiss.fvec_renorm_L2(d, nx, x)
TypeError: in method 'fvec_renorm_L2', argument 3 of type 'float *'

**Comment by hannshu** [comment]
Hi [forrwill](https://github.com/forrwill),

Sorry for this problem; I will fix this problem in the next commit. This problem is due to the incorrect input data type of faiss.
You can also change your data type to np.float32 to fix this problem without waiting for the update.

``` python
# ...
adatas.X = adatas.X.astype(np.float32)
adatas = train_integration(adatas, radius=30, device="cpu")
# ...
```

Han
